config/routes.rb
Blocitoffapi::Application.routes.draw do

 devise_for :users
  resources :users, only: [:update, :show, :index]

  resources :lists do
    resources :tasks

  end


  namespace :api do
    resources :users, only: [:update, :show, :index]
    resources :lists do
      resources :tasks
    end
  end



  
  



  authenticated :user do
    root to: 'lists#index', as: 'authenticated_root'
  end

  get 'about' => 'welcome#about'
  
  root to: 'welcome#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  
  has_many :tasks, dependent: :destroy
  belongs_to :user

  default_scope { order('created_at DESC') }
end

app/models/task.rb
class Task < ActiveRecord::Base
  #require 'active_support'
  belongs_to :list
    

  def due_date
    Date.today - (self.created_at.to_date)
  end

  def days_remaining
   (7 - due_date).to_i
  end

end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base

  #before_create :set_auth_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  #before_save :ensure_authentication_token

  has_many :lists, dependent: :destroy
  has_many :tasks, through: :lists

  

  private
    def set_auth_token
      return if auth_token.present?
      self.auth_token = generated_auth_token
    end

    def generate_auth_token
      SecureRandom.uuid.gsub(/\-/,'')
    end


end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  
  before_filter :authenticate_user
  skip_before_action :verify_authenticity_token

  # necessary in all controllers that will respond with JSON
  respond_to :json, :xml

  private

    def authenticate_user
      @current_user = User.find_by_authentication_token(params[:token])
      unless @current_user
        respond_with({:error => "Token is invalid."})
      end
    end

    def current_user
      @current_user
    end

    def authorize_admin!
      if !@current_user.admin?
        error = { :error => "You must be an admin to do that."}
        warden.custom_failure!
        render params[:format].to_sym => error, :status => 401
      end
    end

  # Error responses and before_action blocking work differently with Javascript requests.
  # Rather than using before_actions to authenticate actions, we suggest using
  # "guard clauses" like `permission_denied_error unless condition`
  def permission_denied_error
   error(403, 'Permission Denied!')
  end

  def error(status, message = 'Something went wrong')
   response = {
    response_type: "ERROR",
      message: message
    }

    render json: response.to_json, status: status
  end

end

app/controllers/api/list_controller.rb
class Api::ListsController < Api::BaseController
  
  before_action :authenticate
  before_filter :authorize_admin!, :except => [:index, :show]

  def index
    lists = List.all
    render json: lists, status: 200
  end

  def create
    list = List.new(params[:list])
    if list.save
      respond_with(list, :location => api_list_path(list))
    else
      respond_with(list)
    end
  end

 protected
    def authenticate
      authenticate_or_request_with_http_token do |token, options|
        User.find_by(auth_token: token)
      end
    end

end

app/controllers/api/users_controller.rb
class Api::UsersController < API::BaseController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
require 'active_support'

  before_filter :authenticate_user_from_token!
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    lists_path
  end

    protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end

    private

   def authorize_admin!
    authenticate_user!
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that!"
      redirect_to root_path
    end
   end 

   def authenticate_user_from_token!
    user_email = params[:user_email].presence
    user       = user_email && User.find_by_email(user_email)
    if user && Devise.secure_compare(user.authentication_token, params[:user_token])
      sign_in user, store: false
    end
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authorize_admin!, :except => [:index, :show]

   def index
    @lists = current_user.lists
    @list = List.new
  end

 def show
    @list = List.find(params[:id])
    @tasks = @list.tasks
    @new_task = Task.new
 end
  
  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.build(list_params)


     if @list.save
       flash[:notice] = "List Saved. Get Crackin!"
       redirect_to @list
     else
       flash[:error] = "You lack the will of a List Warrior. Try again."
       render :new
     end
   end

  def edit
    @list = List.find(params[:id])
  end

  def update
     @list = List.find(params[:id])
     if @list.update_attributes(params.require(:list).permit(:title, :description))
       flash[:notice] = "List updated."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the list. Please try again."
       render :edit
     end
   end


  def destroy
     @list = List.find(params[:id])
     title = @list.title
 
     if @list.destroy
       flash[:notice] = "\"#{title}\" was deleted successfully."
       redirect_to lists_path
     else
       flash[:error] = "There was an error deleting the list."
       render :show
     end
  end

   private

   def list_params
    params.require(:list).permit(:title, :description)
   end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :js
  
  def show
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
  end

  def new
    @list = List.find(params[:list_id])
    @task = Task.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(task_params)
    @new_task = Task.new
    
    if @task.save
      flash[:notice] = "New Task."
      #redirect_to [@list, @tasks]
    else
      flash[:error] = "Nothing saved. Try again."
      #render :edit
    end

      respond_with(@task) do |format|
       format.html { redirect_to @list }
     end
  end


  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
  end

  def update
     @list = List.find(params[:list_id])
     @task = Task.find(params[:id])
    

    if  @task.update_attributes(task_params)
      flash[:notice] = "Task updated. Get back to work!"
      redirect_to @list
    else
      flash[:error] = "No can do, partner. Try again."
      render :edit
    end

  end

 def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    
    if @task.destroy
      flash[:notice] = "One down. More to go."
      #redirect_to @list
    else
      flash[:error] = "Not done yet son."
      #redirect_to @task
    end
     
      respond_with(@task) do |format|
       format.html { redirect_to @list }
     end
  end



  private

    def task_params
      params.require(:task).permit(:title, :body)
    end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
   before_action :authenticate_user!
 
    def show
      @user = User.find(params[:id])
      @lists = @user.lists.paginate(page: params[:page], per_page: 10)
     end 

   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path(current_user)
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
 
   private
 
   def user_params
     params.require(:user).permit(:name)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_name
    "Tate Price aka Voltron"
  end


  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form_group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tater's To Do</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
       <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
          <% if current_user %>
          <li><%= link_to "My Lists", lists_path %></li>

        <% end %>      

           <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

       </ul>

         <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

         

    <%= yield %>
     </div>

</body>
</html>

app/views/lists/edit.html.erb
<h1>Edit List</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Suggestions for Your List</p>
     <ul>
       <li>Make sure you can get it done.</li>
       <li>Prioritize accordingly.</li>
       <li>The tough stuff should come first.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control'%>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control' %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/lists/index.html.erb
<h1>All Lists</h1>

<div class = "row">
  <div class="col-md-8">
    <%= link_to "New List", new_list_path, class: 'btn btn-success' %>
  </div>
</div>

<hr />

<div class="row">
  <div class="col-md-8">
<% @lists.each do |list| %>
  <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to list.title, list %>
       </h4>
        <%= list.description %>
      </br>
      <small>
        submitted <%= time_ago_in_words(list.created_at) %> ago by <%= list.user.name %><br/>
         <%= pluralize(list.tasks.count, 'Task') %> 
         <br/>
         <% if list.tasks.where(overdue: true).any? %>
            <div class="alerts"><%= pluralize(list.tasks.where(overdue: true).count, 'Overdue Task') %>
         </div>
         <% end %>
       </small>
     </div>
   </div>
   <% end %>
  </div>
  </div>

app/views/lists/new.html.erb
<h1>New List</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Suggestions for Your List</p>
     <ul>
       <li>Make sure you can get it done.</li>
       <li>Prioritize accordingly.</li>
       <li>The tough stuff should come first.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @list do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "List Title Here" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "List Description" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/lists/show.html.erb
<div class="row", align=center>
<h1><%= @list.title %></h1>
<h2><small><%= @list.description %></small></h2>

  <%= link_to "Edit List", edit_list_path, class: 'btn btn-success' %>

    <p><strong><div class="top-padding">You have work to do!</div></strong></p>

    <div class="panel panel-primary">
      <div class="panel-body">
      <strong>
    <div class="col-sm-3 text-center"> Task Title </div>
    <div class="col-sm-2 text-left"> Description </div>
    <div class="col-sm-2 text-left"> Days left to Complete </div>
    <div class="col-sm-2 text-center"> Task Complete? </div>
    <div class="col-sm-2 text-center"> Overdue? </div>
    </strong>
    </div>
    </div>
    <div class="jumbotron", align=center>
      <div class="container">
        <div class='js-tasks'> 
        <%= render @tasks %>
        </div>
      </div>
    </div>
    <div class='new-task'>
  <p><strong><div class="top-padding">Want more?</div></strong></p>
    <%= render "tasks/form" %>
 
      <%= link_to "Delete List", @list, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this list?' } %>
    </div>

app/views/tasks/_form.html.erb
 <%= form_for [@list, @new_task], remote: true do |f| %>
<h3><div class="new">New Task</div></h3>
<h4><u>Suggestions for tasks</u></h4>

<div class="row", align=center>
  <div class="col-md-4">You have 7 days. Like The Ring.</div>
    <div class="col-md-4">Get it done.</div>
    <div class="col-md-4">The journey of a thousand miles begins with this task.</div>
  </div>
<br/>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter task name" %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter task description" %>

  <div class="form-group top-padding">
    <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="media">
 <%= content_tag :div, class: 'media', id: "task-#{task.id}" do %> 
    <div class="row">
      <div class="col-lg-2 text-center">
        <%= link_to task.title, [task.list, task] %>
    </div>
    <div class="col-md-3 text-center">
    <em><%= task.body %> </em>
    </div>
    <div class="col-md-2">
    <b><%= task.days_remaining %>
      </b></div>
      <div class="col-md-2 text-right j-padding">
    <%= link_to "Complete", [task.list, task], method: :delete, remote: true, class: 'btn btn-info btn-s', data: { confirm: 'Are you sure this is complete?' } %>
      </div>
     <%if task.overdue? %>
    <div class="col-md-2 alerts text-right"><strong>OVERDUE</div></strong>
       <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/create.js.erb
<% if @task.valid? %>
  $('.js-tasks').append("<%= escape_javascript(render(@task)) %>");
  $('.new-task').html("<%= escape_javascript(render( partial: 'tasks/form', locals: { list: @list, task: @new_task }) ) %>");
<% else %>
  $('.new-task').html("<%= escape_javascript(render partial: 'tasks/form', locals: { list: @list, task: @task }) %>");
<% end %>

app/views/tasks/destroy.html.erb
<%= task.destroy %>

app/views/tasks/destroy.js.erb
 <% if @task.destroyed? %>
   $('#task-' + <%= @task.id %>).fadeOut();
   $('.js-tasks-count').html("<%= @task.list.tasks.count %> tasks");
 <% else %>
   $('#task-' + <%= @task.id %>).append("<div class='alert alert-error'><%= flash[:error] %></div>");
 <% end %>

app/views/tasks/edit.html.erb
<div class="row", align=center>
<h3><div class="new">Current Task</div></h3>
<h4><u>Suggestions for tasks</u></h4>

<div class="row", align=center>
  <div class="col-md-4">You have 7 days. Like The Ring.</div>
    <div class="col-md-4">Get it done.</div>
    <div class="col-md-4">The journey of a thousand miles begins with this task.</div>
  </div>
<br/>

  <div class="media", align=center>
    <div class="form-group">
   <%= form_for [@task.list, @task] do |f| %>
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control'%>
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control' %>
       </div>
       <div class="form-group top-padding">
    <%= f.submit "Update", class: 'btn btn-success' %>
       </div>
    
   <div class="row">
   <h4>Days Left To Complete: <%= @task.days_remaining %></h4>
 </div>
     <%if @task.overdue? %>
    <div class="col-md-8 alerts"><h2>OVERDUE</h2></div>
       <% end %>
  </div>  
  <%= link_to "Complete", [@list, @task], method: :delete, class: 'btn btn-info btn-s', data: { confirm: 'Are you sure this is complete?' } %>
  </div>
  <div class="top-padding text-center">
  <%= link_to "Delete task", [@list, @task], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this task?' } %>
  <% end %>
  </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<div class="row">
  <div class="col-md-4">
    <p>Suggestions for tasks</p>
    <ul>
      <li>You have 7 days. Like The Ring.</li>
      <li>Get it done.</li>
      <li>The journey of a thousand miles begins with this task.</li>
    </ul>
  </div>
  <div class="col-md-8">
  <%= render partial: 'form', locals: { list: @list, task: @task } %>
   </div>
 </div>

app/views/tasks/show.html.erb
<div class="row", align=center>
<h3><div class="new">Current Task</div></h3>
<h4><u>Suggestions for tasks</u></h4>

<div class="row", align=center>
  <div class="col-md-4">You have 7 days. Like The Ring.</div>
    <div class="col-md-4">Get it done.</div>
    <div class="col-md-4">The journey of a thousand miles begins with this task.</div>
  </div>
<br/>

  <div class="media", align=center>
    <div class="form-group">
   <%= form_for [@list, @task] do |f| %>
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control'%>
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control' %>
       </div>
       <div class="form-group top-padding">
    <%= f.submit "Update", class: 'btn btn-success' %>
       </div>
    
   <div class="row">
   <h4>Days Left To Complete: <%= @task.days_remaining %></h4>
 </div>
     <%if @task.overdue? %>
    <div class="col-md-8 alerts"><h2>OVERDUE</h2></div>
       <% end %>
  </div>  
  <%= link_to "Complete", [@list, @task], method: :delete, class: 'btn btn-info btn-s', data: { confirm: 'Are you sure this is complete?' } %>
  </div>
  <div class="top-padding text-center">
  <%= link_to "Delete task", [@list, @task], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this task?' } %>
  <% end %>
  </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="media">
   <%= link_to user, class: 'pull-left' do %>
   <% end %>
   <div class="media-body">
     <h4 class="media-heading">
       <%= link_to user.name, user %>
     </h4>
     <small>
       <%= pluralize(user.lists_count, 'list') %>,
       <%= pluralize(user.tasks_count, 'task') %>
     </small>
   </div>
 </div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
        <div class="media-body">
          <h2 class="media-heading"><%= @user.name %></h2>
          <small>
            <%= pluralize(@user.lists.count, 'list') %>
          </small>
        </div>
      </div>
    </div>
  </div>

</br>

 <div class="row">
   <div class="tabbable tabs-left">
     <ul class="nav nav-tabs">
       <li class="active"><a href="#posts" data-toggle="tab">Lists</a></li>
       <li><a href="#comments" data-toggle="tab">Tasks</a></li>
     </ul>
     <div class="tab-content">
       <div class="tab-pane active" id="posts">
         <%= render @lists %>
       </div>
       <div class="tab-pane" id="comments">
         <%= render @tasks %>
       </div>
     </div>
   </div>
 </div>

app/views/welcome/about.html.erb
<h1>Voltron's List of Conquering</h1>
<p>Make a list, create tasks and stop Dilly Dallying!!!</p>

app/views/welcome/index.html.erb
<center><div class="jumbotron", align=center>
  <div class="container">
  <h1>Welcome to Tater's To-Do</h1>
  <p>Time to get things done</p>
  <p>
    <% if current_user %>
    <span class="glyphicon glyphicon-ok"></span>
    <span class="glyphicon glyphicon-ok"></span>
    <span class="glyphicon glyphicon-ok"></span>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info' %>
    <%end%>
  </p>
</div>
</div>
<div class="column">
  <div class="col-md-4">
    <h3>Track your tasks.</h3>
  </div>
  <div class="col-md-4 col-md-offset-4">
    <h3>Be on point.</h3>
  </div>
  </div>
  <div class="column">
  <div class="col-md-6 col-md-offset-3">
    <h2>Change the world.</h2>
  </div></center>